### PR TITLE
Hibernate reactive, Hibernate reactive panache and Reactive sql client examples

### LINKED ISSUE #9: Fix ripe Hibernate Reactive example
Ripe transaction is not bieng commited so the validation is failing.

```
2021-09-18 13:18:13,339 ERROR [io.qua.test] (Test runner thread) ==================== TEST REPORT #1 ====================
2021-09-18 13:18:13,339 ERROR [io.qua.test] (Test runner thread) Test FruitReactiveResourceTest#testFruitRipeReactive() failed 
: java.lang.AssertionError: 1 expectation failed.
Response body doesn't match expectation.
Expected: a string containing "\"ripen\":true"
  Actual: {"name":"pear","description":"Pear","family":"Rosaceae","ripen":false}

        at io.restassured.internal.ValidatableResponseImpl.body(ValidatableResponseImpl.groovy)
        at com.trikorasolutions.example.FruitReactiveResourceTest.testFruitRipeReactive(FruitReactiveResourceTest.java:94)

2021-09-18 13:18:13,345 ERROR [io.qua.test] (Test runner thread) >>>>>>>>>>>>>>>>>>>> 1 TEST FAILED <<<<<<<<<<<<<<<<<<<<
1 test failed (3 passing, 0 skipped), 4 tests were run in 5777ms. Tests completed at 13:18:13.
```

### PR DESCRIPTION
**Pull request by SirSkizo**
Closes #9

### CODE REVIEW

File: reactive-mysql-client/src/main/java/com/trikorasolutions/example/logic/FruitLogic.java [hunk 1]
```diff
@@ -0,0 +1,31 @@
...
+public class FruitLogic {
+  private static final Logger LOGGER = LoggerFactory.getLogger(FruitLogic.class);
+
+  @Inject
+  io.vertx.mutiny.mysqlclient.MySQLPool sqlPool;
+
+  @Inject
+  FruitRepository repoFruit;
+
+  //TODO: make the sql statement persist without munity
```
Comment (jacobdotcosta) [inline reactive-mysql-client/src/main/java/com/trikorasolutions/example/logic/FruitLogic.java:23]: Remove this comment TODO.

**Review by jacobdotcosta — APPROVED** [review]
